title: Claude活用事例集
description: 海外のClaude活用事例を日本語で紹介
baseurl: "/claude-examples-jp"  # リポジトリ名に合わせて変更
url: "https://あなたのユーザー名.github.io"  # あなたのGitHubユーザー名に変更
github_username: あなたのユーザー名  # あなたのGitHubユーザー名に変更

# ビルド設定
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - .gitignore
