name: 自動コンテンツ更新

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日実行（UTCの0時 = 日本時間の朝9時頃）
  workflow_dispatch:  # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        
      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 依存パッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdown
          
      - name: データを収集
        run: python scripts/collect_data.py
        
      - name: コンテンツを生成
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: python scripts/generate_content.py
        
      - name: サイト設定ファイルの作成
        run: |
          # Gemfileの作成
          echo 'source "https://rubygems.org"' > Gemfile
          echo 'gem "github-pages", group: :jekyll_plugins' >> Gemfile
          
          # インデックスページの作成
          cat > index.md << 'EOF'
          ---
          layout: home
          title: ホーム
          ---

          # Claude活用事例集

          このサイトでは、世界中のClaude AIの活用事例を自動的に収集し、日本語で解説しています。
          
          最新の活用方法をチェックして、あなたのプロジェクトに応用してみましょう！
          EOF
          
          # 404ページの作成
          cat > 404.html << 'EOF'
          ---
          layout: default
          title: ページが見つかりません
          ---

          <div style="text-align: center; padding: 60px 0;">
            <h1>404</h1>
            <p>お探しのページは見つかりませんでした。</p>
            <p><a href="{{ '/' | relative_url }}">ホームに戻る</a></p>
          </div>
          EOF
          
          # about.mdの作成
          cat > about.md << 'EOF'
          ---
          layout: page
          title: サイトについて
          permalink: /about/
          ---

          このサイトは、Claude AIの活用事例を自動収集して紹介するウェブサイトです。

          ## 目的

          海外で公開されているClaude AIの活用事例を日本語で紹介し、日本のユーザーがClaude AIをより効果的に活用できるようにすることを目指しています。

          ## 仕組み

          このサイトは、GitHub Pagesを使って公開されており、以下の仕組みで運営されています：

          1. 自動データ収集：GitHubやその他のソースからClaude関連の情報を収集
          2. AI記事生成：Claude APIを使って収集した情報から記事を自動生成
          3. 定期的な更新：毎日新しい情報を自動で収集・公開
          EOF
        
      - name: GitHub Pagesをセットアップ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          
      - name: 変更をコミットしてプッシュ
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "コンテンツを更新"
          git push
